added file with completed homework_4
eugene-okulik/elosnoc pull request #4
Opened 2024-12-06 14:48 UTC by oleelosnoc

2024-12-07 09:00 UTC, eugene-okulik requested changes
Всё отлично, но проверку на внимательность не прошел )))

2024-12-07 09:00 UTC, eugene-okulik commented on homework/siarhei_shcharbin/homework_4/task_1.py
> +my_dict['dict']['i am a tuple'] = 'it is not a typo'
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-12-07 12:34 UTC, oleelosnoc commented on homework/siarhei_shcharbin/homework_4/task_1.py
> +my_dict['dict']['i am a tuple'] = 'it is not a typo'
да, был немного невнимателен
поправил

2024-12-08 11:17 UTC, eugene-okulik approved these changes

2024-12-08 11:17 UTC, merged