added 3 files with completed homework_5
eugene-okulik/elosnoc pull request #5
Opened 2024-12-09 22:33 UTC by oleelosnoc

2024-12-10 07:03 UTC, eugene-okulik requested changes

2024-12-10 07:03 UTC, eugene-okulik commented on homework/siarhei_shcharbin/homework_5/task_2.py
> +a_num_pos = a.index('42')
Если еще в момент написания программы мы знаем, что в строке будет число 42, то мы можем написать просто print(42 + 10)  
Заморочка в том, чтобы найти в этой строке число, каким бы оно там ни было. Для этого нужно найти в этих строках что-то одинаковое: количество символов перед числом разное; количество символов в числе тоже разное. Но есть в структуре всех строк что-то одинаковое и на это можно опереться.  
В примерах - варианты того, как может ответить программа. Вместо числа 42 может оказаться число 28346473, вместо 514 число 3. Нам нужно сделать один код, который сможет работать с любым из вариантов ответа. То есть обработать каждую переменную абсолютно одинаковым кодом. Пока что делаем это копируя код, потом будем учиться как избежать здесь этого копирования.

2024-12-10 09:49 UTC, oleelosnoc commented on homework/siarhei_shcharbin/homework_5/task_2.py
> +a_num_pos = a.index('42')
Так и знал, что не так все просто в задании)
Поправил код, унифицировал для любого инпута данных темплейтов.

2024-12-11 06:07 UTC, eugene-okulik approved these changes

2024-12-11 06:07 UTC, merged